name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle Build
        run: ./gradlew packageDistributionForCurrentOS
      #      - name: Archive Artifacts
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: distributable-${{ matrix.os }}
      #          if-no-files-found: ignore
      #          path: |
      #            build/**/*.deb
      #            build/**/*.msi
      #            build/compose/jars/*.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/compose/binaries/**/*.deb
            build/compose/binaries/**/*.msi
            build/compose/binaries/**/*.dmg
