name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Extract tag on Unix
        if: runner.os != 'Windows'
        run: echo "tag=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      # Extract Tag for Windows
      - name: Extract tag on Windows
        if: runner.os == 'Windows'
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo "tag=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
      - name: Run Gradle Build
        run: ./gradlew packageDistributionForCurrentOS -Pversion="${{ env.tag }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/compose/binaries/**/*.deb
            build/compose/binaries/**/*.msi
            build/compose/binaries/**/*.dmg
