name: Test Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle Tests
        run: ./gradlew test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
