name: Test Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle Tests
        run: ./gradlew test
